name: Update Kong Gateway with decK

on:
  push:
    branches:
      - main  # Change this to the branch you want to monitor for updates

jobs:
  sync-deck:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Download and Install decK
    - name: Install decK
      run: |
        DECK_VERSION=1.15.0  
        curl -Lo deck.tar.gz https://github.com/kong/deck/releases/download/v${DECK_VERSION}/deck_${DECK_VERSION}_linux_amd64.tar.gz
        tar -xvf deck.tar.gz
        chmod +x deck
        sudo mv deck /usr/local/bin/deck
        deck version 


    # Step 3: Run decK sync
    - name: Sync Kong Gateway
      env:
        KONNECT_TOKEN: kpat_Fz7BgrgqhY1f8TuQpVeNpp47YpppeMN4hkHZkKHlDJrQb40km
      run: deck gateway sync --konnect-token kpat_Fz7BgrgqhY1f8TuQpVeNpp47YpppeMN4hkHZkKHlDJrQb40km ./kong-gateway.yaml
